# Generated by Django 4.1.1 on 2022-11-04 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegado',
            fields=[
                ('id_delegado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_delegado', models.CharField(max_length=50, null=True)),
                ('ci_delegado', models.CharField(max_length=15, null=True)),
                ('nacimiento_delegado', models.DateField(null=True)),
                ('telefono_delegado', models.CharField(max_length=15, null=True)),
                ('foto_delegado', models.ImageField(null=True, upload_to='static/imagenes/equipos/delegados', verbose_name='Foto Delegado')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entrenador', models.CharField(max_length=50, null=True)),
                ('apodo_entrenador', models.CharField(max_length=50, null=True)),
                ('nacionalidad_entrenador', models.CharField(max_length=50, null=True)),
                ('ci_entrenador', models.CharField(max_length=50, null=True)),
                ('nacimiento_entrenador', models.DateField()),
                ('foto_entrenador', models.ImageField(null=True, upload_to='static/imagenes/equipos/entrenadores/', verbose_name='Foto Enrtenador')),
                ('telefono_entrenador', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=50, null=True)),
                ('pais_origen', models.CharField(max_length=50, null=True)),
                ('ciudad_origen', models.CharField(max_length=50, null=True)),
                ('escudo_equipo', models.ImageField(null=True, upload_to='static/imagenes/equipos/escudos/', verbose_name='Escudo equipo')),
                ('portada_equipo', models.ImageField(null=True, upload_to='static/imagenes/equipos/portadas/', verbose_name='Foto equipo')),
                ('categoria_equipo', models.CharField(max_length=50, null=True)),
                ('estado_inscripcion_equipo', models.CharField(max_length=50, null=True)),
                ('id_delegado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneo.delegado')),
                ('id_entrenador_equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneo.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizador', models.CharField(max_length=50)),
                ('correo_organizador', models.CharField(max_length=30)),
                ('telefono_organizador', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['nombre_organizador'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_torneo', models.CharField(max_length=50)),
                ('fecha_torneo_inicio', models.DateField(null=True)),
                ('fecha_torneo_fin', models.DateField(null=True)),
                ('pais_torneo', models.CharField(max_length=30)),
                ('torneo_estado', models.BooleanField(default=True)),
                ('invitacion_documento', models.FileField(upload_to='static/imagenes/convocatorias/', verbose_name='Convocatoria')),
                ('logo', models.ImageField(null=True, upload_to='static/imagenes/logos/', verbose_name='LogoTorneo')),
                ('id_organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.organizador')),
            ],
        ),
        migrations.CreateModel(
            name='Pre_Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicioPre', models.DateField()),
                ('fecha_finPre', models.DateField()),
                ('monto_Preinscripcion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_Preinscripcion', models.ImageField(null=True, upload_to='static/imagenes/qrs/', verbose_name='qr1')),
                ('estado_Preinscripcion', models.BooleanField(default=True)),
                ('id_torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(max_length=50, null=True)),
                ('apodo_jugador', models.CharField(max_length=50, null=True)),
                ('ci_jugador', models.CharField(max_length=50, null=True)),
                ('nacimiento_jugador', models.DateField()),
                ('foto_jugador', models.ImageField(null=True, upload_to='static/imagenes/equipos/jugadores/', verbose_name='Foto jugador')),
                ('telefono_jugador', models.CharField(max_length=50, null=True)),
                ('dorsal_jugador', models.CharField(max_length=5, null=True)),
                ('posicion_jugador', models.CharField(max_length=50, null=True)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_inscripcion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_inscripcion', models.ImageField(null=True, upload_to='static/imagenes/qrs/', verbose_name='qr2')),
                ('estado_inscripcion', models.BooleanField(default=False)),
                ('id_torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_torneo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo'),
        ),
        migrations.CreateModel(
            name='delegado_PreInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_delegado_Preinscripcion', models.CharField(max_length=50)),
                ('estado_delegado_Preinscripcion', models.CharField(max_length=15)),
                ('correo_delegado_Preinscripcion', models.CharField(max_length=50)),
                ('ci_delegado_Preinscripcion', models.CharField(max_length=15)),
                ('telefono_delegado_Preinscripcion', models.CharField(max_length=15)),
                ('recibo_Preinscripcion', models.ImageField(null=True, upload_to='static/imagenes/Comprobantes/', verbose_name='Recibo Preinscripción')),
                ('id_Pre_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.pre_inscripcion')),
                ('id_delegadoPreIns', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='delegado_Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_delegado_inscripcion', models.CharField(max_length=50)),
                ('estado_delegado_inscripcion', models.CharField(max_length=15)),
                ('correo_delegado_inscripcion', models.CharField(max_length=50)),
                ('ci_delegado_inscripcion', models.CharField(max_length=15)),
                ('telefono_delegado_inscripcion', models.CharField(max_length=15)),
                ('recibo_inscripcion', models.ImageField(null=True, upload_to='static/imagenes/Comprobantes/', verbose_name='Recibo Rezagados')),
                ('id_delegadoIns', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Categorias_Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=20)),
                ('edad_minima', models.IntegerField()),
                ('edad_maxima', models.IntegerField()),
                ('id_torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
    ]
