# Generated by Django 4.1 on 2022-11-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_delegado_inscripcion_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_posiciones',
            fields=[
                ('id_equipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=50, null=True)),
                ('categoria_equipo', models.CharField(max_length=50, null=True)),
                ('partidos_jugados', models.IntegerField(null=True)),
                ('partidos_ganados', models.IntegerField(null=True)),
                ('partidos_perdidos', models.IntegerField(null=True)),
                ('puntos_favor', models.IntegerField(null=True)),
                ('puntos_encontra', models.IntegerField(null=True)),
                ('puntaje_total', models.IntegerField(null=True)),
                ('id_torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
    ]
