# Generated by Django 4.1 on 2022-11-09 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0004_tabla_posiciones_diferencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfrentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_a', models.CharField(max_length=50, null=True)),
                ('equipo_b', models.CharField(max_length=50, null=True)),
                ('fecha_enfrentamiento', models.DateTimeField(null=True)),
                ('id_torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
    ]
