# Generated by Django 4.1 on 2022-11-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0005_enfrentamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfrentamiento',
            name='categoria',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
