# Generated by Django 4.1 on 2022-11-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0007_enfrentamiento_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfrentamiento',
            name='escudo_equipoA',
            field=models.ImageField(null=True, upload_to='static/imagenes/equipos/escudos/', verbose_name='Escudo equipo'),
        ),
        migrations.AddField(
            model_name='enfrentamiento',
            name='escudo_equipoB',
            field=models.ImageField(null=True, upload_to='static/imagenes/equipos/escudos/', verbose_name='Escudo equipo'),
        ),
    ]
