# Generated by Django 4.1 on 2022-11-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0008_enfrentamiento_escudo_equipoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfrentamiento',
            name='puntajeEquipoA',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enfrentamiento',
            name='puntajeEquipoB',
            field=models.IntegerField(null=True),
        ),
    ]
