# Generated by Django 4.1 on 2022-11-22 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0009_enfrentamiento_puntajeequipoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='anotaciones',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='faltas',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Estadisticas_enfrentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faltas', models.IntegerField(null=True)),
                ('anotaciones', models.IntegerField(null=True)),
                ('id_enfrentamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.enfrentamiento')),
                ('id_jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.jugador')),
            ],
        ),
    ]
