# Generated by Django 4.1.3 on 2022-11-24 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0010_jugador_anotaciones_jugador_faltas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegado_inscripcion',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='delegado_preinscripcion',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
