# Generated by Django 4.1.3 on 2022-11-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0011_alter_delegado_inscripcion_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias_torneo',
            options={'verbose_name_plural': 'Categorias de torneo'},
        ),
        migrations.AlterModelOptions(
            name='delegado',
            options={'verbose_name_plural': 'Delegados'},
        ),
        migrations.AlterModelOptions(
            name='delegado_inscripcion',
            options={'verbose_name_plural': 'Delegado inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='delegado_preinscripcion',
            options={'verbose_name_plural': 'Delegado preinscripciones'},
        ),
        migrations.AlterModelOptions(
            name='enfrentamiento',
            options={'verbose_name_plural': 'Enfrentamientos'},
        ),
        migrations.AlterModelOptions(
            name='entrenador',
            options={'verbose_name_plural': 'Entrenadores'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='estadisticas_enfrentamiento',
            options={'verbose_name_plural': 'Estadisticas de enfrentamientos'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name_plural': 'Inscripcion'},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='organizador',
            options={'ordering': ['nombre_organizador'], 'verbose_name_plural': 'Organizadores'},
        ),
        migrations.AlterModelOptions(
            name='pre_inscripcion',
            options={'verbose_name_plural': 'Preinscripcion'},
        ),
        migrations.AlterModelOptions(
            name='tabla_posiciones',
            options={'verbose_name_plural': 'Tabla de posiciones'},
        ),
        migrations.AlterModelOptions(
            name='torneo',
            options={'verbose_name_plural': 'Torneos'},
        ),
    ]
