# Generated by Django 4.1.3 on 2022-11-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0012_alter_categorias_torneo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizador',
            options={'verbose_name_plural': 'Organizadores'},
        ),
    ]
