# Generated by Django 4.1.3 on 2022-11-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0013_alter_organizador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizador',
            options={'ordering': ['nombre_organizador'], 'verbose_name_plural': 'Organizadores'},
        ),
    ]
