# Generated by Django 4.1.3 on 2022-11-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0014_alter_organizador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizador',
            options={'verbose_name_plural': 'Organizadores'},
        ),
    ]
